---
title: "Assignment 1"
author: "PLSC 31101"
date: "Fall 2020"
output: html_document
---

## Assignment 1

- __Assigned__: September 30.
- __Due__: October 7 by 11:59pm.

For this assignment, you will confirm that everything is installed and setup correctly, and you understand how to interact with R Studio and R Markdown. 

Your answers (to this assignment only) will be posted on our [course website](https://github.com/rochelleterman/plsc-31101).

#### 1. Using R Markdown {-}

In the space below, insert a picture of yourself, and complete the following information:

`[your picture here]`

1. __Name__: 
2. __Department and degree program__:
3. __Year in the program__:
4. __One-sentence description of academic interests__:
5. __Some non-academic interests__:
6. __R version installed on your computer__ (Open a command line window ('terminal' or, on windows, 'git bash'), and enter the following command `R --version`):
7. __R Studio version installed on your computer__ (Open RStudio and, in the navigation menu, click on RStudio --> About RStudio):
8. __Primary computer operating system__ (Mac OS, Windows, Linux, etc):
9. __Programming experience__ (How would you describe your previous programming experience?):

#### 2. Checking packages {-}

Create an R chunk below, where you load the `tidyverse` library.

#### 3. Knit and submit. {-}

Knit the R Markdown file to PDF. Submit __BOTH__ the .Rmd file and the PDF file to Canvas. 

If you get an error trying to knit, read the error and make sure that your R code is correct. If that doesn't work, confirm you've correctly installed the requisite packages (`knitr`, `rmarkdown`). If you still can't get it to work, paste the error on Canvas. 
